CREATE TABLE USUARIO (
  ID INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  LOGIN VARCHAR  NULL  ,
  SENHA VARCHAR  NULL    ,
PRIMARY KEY(ID));



CREATE TABLE BILL (
  ID INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  USUARIO_ID INTEGER UNSIGNED  NOT NULL  ,
  BENEFICIARIO VARCHAR  NULL  ,
  VALOR REAL  NULL DEFAULT 0 ,
  DEVEDOR VARCHAR  NULL  ,
  MOTIVO VARCHAR  NULL  ,
  DATA_CONTA DATE  NULL  ,
  ESTADO VARCHAR  NULL    ,
PRIMARY KEY(ID)  ,
INDEX BILL_FKIndex1(USUARIO_ID),
  FOREIGN KEY(USUARIO_ID)
    REFERENCES USUARIO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE HISTORICO_ALTERACAO (
  ID INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  USUARIO_ID INTEGER UNSIGNED  NOT NULL  ,
  BILL_ID INTEGER UNSIGNED  NOT NULL  ,
  BENEFICIARIO VARCHAR  NULL  ,
  VALOR REAL  NULL DEFAULT 0 ,
  DEVEDOR VARCHAR  NULL  ,
  MOTIVO VARCHAR  NULL  ,
  DATA_CONTA DATE  NULL  ,
  ESTADO VARCHAR  NULL    ,
PRIMARY KEY(ID)  ,
INDEX HISTORICO_ALTERACAO_FKIndex1(BILL_ID)  ,
INDEX HISTORICO_ALTERACAO_FKIndex2(USUARIO_ID),
  FOREIGN KEY(BILL_ID)
    REFERENCES BILL(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(USUARIO_ID)
    REFERENCES USUARIO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);




